version: '3.1'

services:
  joomla:
    build:
      context: joomla370
      dockerfile: Dockerfile_install
    ports:
      - 8080:80
    volumes:
      - ./joomla370/app:/var/www/html

    depends_on:
      - mariadb
  mariadb:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: root
