apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: mariadb370
  name: mariadb370
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mariadb370
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: mariadb370
    spec:
      containers:
        - image: darthos/joomla_db:0.3
          name: mariadb370
          ports:
            - containerPort: 3306
          resources: {}
      restartPolicy: Always
status: {}
